INSERT INTO books (id,
                   title,
                   author,
                   year,
                   cost,
                   discount,
                   publisher,
                   description,
                   amount)
VALUES (gen_random_uuid(),
        'Мастер и Маргарита',
        'Михаил Булгаков',
        1967,
        18.90,
        10,
        'АСТ',
        'Роман о дьяволе, посетившем Москву, и о судьбах людей, столкнувшихся с мистикой.',
        40),

       (gen_random_uuid(),
        'Преступление и наказание',
        'Фёдор Достоевский',
        1866,
        15.50,
        NULL,
        'Эксмо',
        'История студента Раскольникова, совершившего преступление и переживающего моральные муки.',
        35),

       (gen_random_uuid(),
        'Война и мир',
        'Лев Толстой',
        1869,
        29.99,
        15,
        'Азбука',
        'Эпический роман о судьбах людей во времена Наполеоновских войн.',
        20),

       (gen_random_uuid(),
        'Анна Каренина',
        'Лев Толстой',
        1877,
        22.40,
        NULL,
        'Азбука',
        'Трагическая история любви Анны Карениной и офицера Вронского.',
        25),

       (gen_random_uuid(),
        'Тихий Дон',
        'Михаил Шолохов',
        1940,
        24.80,
        5,
        'Эксмо',
        'Роман о жизни донских казаков в годы революции и гражданской войны.',
        18),

       (gen_random_uuid(),
        'Мы',
        'Евгений Замятин',
        1924,
        13.70,
        NULL,
        'АСТ',
        'Антиутопический роман о тоталитарном государстве будущего.',
        30),

       (gen_random_uuid(),
        'Пикник на обочине',
        'Аркадий и Борис Стругацкие',
        1972,
        17.60,
        8,
        'Азбука',
        'Научно-фантастический роман о загадочной Зоне и сталкерах.',
        28);

INSERT INTO genres (id, genre, book_id)
VALUES (gen_random_uuid(), 'Мистика', (SELECT id FROM books WHERE title = 'Мастер и Маргарита')),
       (gen_random_uuid(), 'Классика', (SELECT id FROM books WHERE title = 'Мастер и Маргарита')),
       (gen_random_uuid(), 'Философия', (SELECT id FROM books WHERE title = 'Мастер и Маргарита')),

       (gen_random_uuid(), 'Классика', (SELECT id FROM books WHERE title = 'Преступление и наказание')),
       (gen_random_uuid(), 'Психология', (SELECT id FROM books WHERE title = 'Преступление и наказание')),
       (gen_random_uuid(), 'Философия', (SELECT id FROM books WHERE title = 'Преступление и наказание')),

       (gen_random_uuid(), 'Классика', (SELECT id FROM books WHERE title = 'Война и мир')),
       (gen_random_uuid(), 'Исторический роман', (SELECT id FROM books WHERE title = 'Война и мир')),

       (gen_random_uuid(), 'Классика', (SELECT id FROM books WHERE title = 'Анна Каренина')),
       (gen_random_uuid(), 'Роман', (SELECT id FROM books WHERE title = 'Анна Каренина')),
       (gen_random_uuid(), 'Драма', (SELECT id FROM books WHERE title = 'Анна Каренина')),

       (gen_random_uuid(), 'Классика', (SELECT id FROM books WHERE title = 'Тихий Дон')),
       (gen_random_uuid(), 'Исторический роман', (SELECT id FROM books WHERE title = 'Тихий Дон')),

       (gen_random_uuid(), 'Антиутопия', (SELECT id FROM books WHERE title = 'Мы')),
       (gen_random_uuid(), 'Фантастика', (SELECT id FROM books WHERE title = 'Мы')),

       (gen_random_uuid(), 'Фантастика', (SELECT id FROM books WHERE title = 'Пикник на обочине')),
       (gen_random_uuid(), 'Научная фантастика', (SELECT id FROM books WHERE title = 'Пикник на обочине')),
       (gen_random_uuid(), 'Приключения', (SELECT id FROM books WHERE title = 'Пикник на обочине'));

INSERT INTO shops (id, name, address)
VALUES (gen_random_uuid(), 'Книжный центр', 'ул. Ленина, 1'),
       (gen_random_uuid(), 'БиблиоМир', 'ул. Пушкина, 5'),
       (gen_random_uuid(), 'Читай-город', 'пр. Мира, 10');